
;; Add ~/.emacs.d/lisp/ to 'load-path;;;load the .el files floder
(add-to-list 'load-path
	     (expand-file-name(concat user-emacs-directory "lisp")))

;; Use 'custom.el to store settinsg generated by UI interface;;
(setq custom-file
      (expand-file-name "custom.el" user-emacs-directory)) 

(require 'init-const)
(require 'init-func)
(require 'init-startup)
(require 'init-elpa)
(require 'init-ui)
(require 'init-package)
(require 'init-kbd)

(when (file-exists-p custom-file)
  (load-file custom-file))


